Fix for 'TypeError: undefined is not a function' when an undefined function call is invoked for a class.
Now, instead of 'undefined' the interpreter will print class.function

Example:
foo = {};
foo.bar();
=> [old output] TypeError: undefined is not a function
=> [new output] TypeError: foo.bar is not a function